_BASE_: Base-ADE20K-SemanticSegmentation.yaml
MODEL:
  META_ARCHITECTURE: "MaskDINO"
  SEM_SEG_HEAD:
    NAME: "MaskDINOHead"
    IGNORE_VALUE: 255
    # NUM_CLASSES: 64
    NUM_CLASSES: 9
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256 # 控制你輸出的大小的，中間過程的hidden_dim不要超過MaskDINODecoder
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MaskDINOEncoder"
    DIM_FEEDFORWARD: 1024
    NUM_FEATURE_LEVELS: 3
    TOTAL_NUM_FEATURE_LEVELS: 3
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 2 # swin
    # COMMON_STRIDE: 4 
    TRANSFORMER_ENC_LAYERS: 6
  MaskDINO:
    TRANSFORMER_DECODER_NAME: "MaskDINODecoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 4.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 3072
    # DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    # DEC_LAYERS: 9  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TWO_STAGE: False
    DN: "seg"
    DN_NUM: 100
    INITIALIZE_BOX_TYPE: "no"
    SEMANTIC_CE_LOSS: True
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
SOLVER:
  AMP:
    ENABLED: False
  BACKBONE_MULTIPLIER: 0.1
  BASE_LR: 0.0001
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5000
  # CHECKPOINT_PERIOD: 18000
  
  IMS_PER_BATCH: 2 # mask_head
  # IMS_PER_BATCH: 1 # 2branch
  # IMS_PER_BATCH: 6 # res50
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  # MAX_ITER: 162000 
  MAX_ITER: 90000


  STEPS: (135000,150000)
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WARMUP_METHOD: linear
